workflows:
  ios_build:
    name: iOS build
    environment:
      groups:
        - react-native
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npx react-native run-ios --configuration Release
    artifacts:
      - build/ios/iphoneos/*.app
