workflows:
  ios-workflow:
    name: iOS Workflow
    platform: ios
    sdk: iphoneos
    trigger:
      events:
        - push
    steps:
      - name: Checkout code
        script: |
          git clone https://github.com/HentaiHeroes.github.io
/iphone.js
          cd iphone.js
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps  # Убедись, что все зависимости установлены
      - name: Build the app
        script: |
          npx react-native run-ios --configuration Release  # Сборка iOS приложения
