workflows:
  ios:
    name: iOS build
    platform: ios
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npx react-native run-ios
