workflows:
  ios_build:
    name: iOS build
    environment:
      flutter: false  # Указываем, что проект не на Flutter
      node: latest    # Указываем, что нужна последняя версия Node.js
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npx react-native run-ios --configuration Release
    artifacts:
      - build/ios/iphoneos/*.app
