workflows:
  ios_build:
    name: iOS build
    platform: ios
    ios:
      xcode_project: path/to/your/project.xcworkspace
      flutter: false
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npx react-native run-ios
